"""Stage 2, schema drift check (see the Stage 2 spec, section 14).

Uses Alembic's own `alembic check` machinery (`alembic.command.check`,
available since Alembic 1.13 - see backend/pyproject.toml's
`alembic>=1.18,<1.19` pin) via its autogenerate comparison against a
database freshly migrated to head. This is not a tautological test: `check`
independently reflects the *live* database and diffs it against
`Base.metadata` (backend/app/core/db_base.py) using the same comparators
`alembic revision --autogenerate` would use - a genuine divergence between
what the migrations produce and what the current SQLAlchemy models declare
raises `alembic.util.exc.AutogenerateDiffsDetected`.

Requires TEST_DATABASE_URL with CREATEDB+CREATEROLE rights - see
tests/stage2_db_helpers.py's module docstring.
"""

import pytest
from alembic import command
from alembic.util.exc import AutogenerateDiffsDetected

from app.db_admin.bootstrap_roles import bootstrap_roles
from tests import stage2_db_helpers as h

pytestmark = pytest.mark.skipif(
    not h.TEST_DATABASE_URL,
    reason="TEST_DATABASE_URL is not set - skipping PostgreSQL integration tests",
)


@pytest.fixture()
def migrated_stage2_database():
    name = h.disposable_database_name("drift")
    h.create_disposable_database(name)
    bootstrap_roles(h.role_bootstrap_config(name))
    cfg = h.alembic_config_for(h.migration_database_url(name))
    command.upgrade(cfg, "head")
    try:
        yield cfg
    finally:
        h.drop_disposable_database(name)


def test_migration_head_matches_current_sqlalchemy_metadata(migrated_stage2_database):
    """`alembic check` must find nothing to generate - if it raises, either a
    model changed without a matching migration, or a migration doesn't
    actually produce what the model declares. Either way, that's real
    drift, not a false positive: this ran against a database that was *just*
    migrated to head by this same test, using the *current* models module
    (backend/app/core/db_base.py's Base.metadata)."""
    command.check(migrated_stage2_database)


def test_a_genuine_drift_is_actually_detected(migrated_stage2_database, monkeypatch):
    """Negative control: if this test ever failed to raise, that would mean
    `alembic check` above is a tautology (e.g. broken metadata wiring) and
    the previous test's pass would be meaningless. Introduces a real,
    deliberate divergence - a column current models don't have - directly
    against the live database, then confirms `alembic check` catches it."""
    from sqlalchemy import create_engine, text

    cfg = migrated_stage2_database
    url = cfg.get_main_option("sqlalchemy.url")
    engine = create_engine(url)
    try:
        with engine.begin() as conn:
            conn.execute(text("ALTER TABLE applications ADD COLUMN drift_test_column INTEGER"))
        with pytest.raises(AutogenerateDiffsDetected):
            command.check(cfg)
    finally:
        with engine.begin() as conn:
            conn.execute(text("ALTER TABLE applications DROP COLUMN drift_test_column"))
        engine.dispose()


# ---------------------------------------------------------------------------
# MAJOR 4 correction: `alembic check` must compare server_default drift, not
# just column type/presence. backend/alembic/env.py now sets
# compare_server_default=True in both context.configure() calls (online and
# offline). Each test below is a negative control in the same spirit as
# test_a_genuine_drift_is_actually_detected above: without that setting,
# `alembic check` reports "No new upgrade operations detected" for all three
# of these - a real, exploitable blind spot (see admins.is_active, which
# app/models/admin.py deliberately gives only a client-side default=True,
# never a server_default - see app/core/schema_introspect.py's callers,
# which both rely on that distinction being real).
# ---------------------------------------------------------------------------


def test_adding_a_server_default_outside_a_migration_is_detected(migrated_stage2_database):
    """admins.is_active has no server_default in current metadata (it's a
    client-side SQLAlchemy default - see app/models/admin.py). Adding one
    directly against the live database is genuine drift and must be caught."""
    from sqlalchemy import create_engine, text

    cfg = migrated_stage2_database
    url = cfg.get_main_option("sqlalchemy.url")
    engine = create_engine(url)
    try:
        with engine.begin() as conn:
            conn.execute(text("ALTER TABLE admins ALTER COLUMN is_active SET DEFAULT true"))
        with pytest.raises(AutogenerateDiffsDetected):
            command.check(cfg)
    finally:
        with engine.begin() as conn:
            conn.execute(text("ALTER TABLE admins ALTER COLUMN is_active DROP DEFAULT"))
        engine.dispose()


def test_removing_a_server_default_outside_a_migration_is_detected(migrated_stage2_database):
    """Opposite direction: admins.created_at DOES have a server_default
    (func.now()) in current metadata. Removing it directly against the live
    database must also be caught, not just additions."""
    from sqlalchemy import create_engine, text

    cfg = migrated_stage2_database
    url = cfg.get_main_option("sqlalchemy.url")
    engine = create_engine(url)
    try:
        with engine.begin() as conn:
            conn.execute(text("ALTER TABLE admins ALTER COLUMN created_at DROP DEFAULT"))
        with pytest.raises(AutogenerateDiffsDetected):
            command.check(cfg)
    finally:
        with engine.begin() as conn:
            conn.execute(text("ALTER TABLE admins ALTER COLUMN created_at SET DEFAULT now()"))
        engine.dispose()


def test_changing_a_server_default_outside_a_migration_is_detected(migrated_stage2_database):
    """Proves the check compares default *content*, not just presence/
    absence: admins.updated_at already has a server_default in current
    metadata (func.now()) - replacing it with a different-but-still-present
    default must still be flagged as drift."""
    from sqlalchemy import create_engine, text

    cfg = migrated_stage2_database
    url = cfg.get_main_option("sqlalchemy.url")
    engine = create_engine(url)
    try:
        with engine.begin() as conn:
            conn.execute(
                text("ALTER TABLE admins ALTER COLUMN updated_at SET DEFAULT '2000-01-01 00:00:00+00'")
            )
        with pytest.raises(AutogenerateDiffsDetected):
            command.check(cfg)
    finally:
        with engine.begin() as conn:
            conn.execute(text("ALTER TABLE admins ALTER COLUMN updated_at SET DEFAULT now()"))
        engine.dispose()
