"""Password hashing, username normalization, and JWT helpers for admin authentication.

Kept free of FastAPI/DB imports (mirrors core/exceptions.py) so it can be unit
tested in isolation and reused by both the CRUD layer and route dependencies.
Never logs or stores a plaintext password anywhere.
"""

import hashlib
import json
import secrets
from datetime import datetime, timedelta, timezone
from typing import Any

import jwt
from argon2 import PasswordHasher
from argon2.exceptions import InvalidHashError, VerificationError, VerifyMismatchError
from argon2.low_level import Type

from app.core.config import get_settings

TOKEN_TYPE_ACCESS = "access"

# Explicit Argon2id profile - deliberately not relying on argon2-cffi's
# built-in defaults, which are tuned for a generic host and can change
# between library releases. These values target this project's backend
# container (docker-compose.yml caps it at 192M / reserves 128M): ~19 MiB
# per hash/verify call at parallelism=1 leaves headroom for a handful of
# concurrent requests without threatening the container limit. Revisit and
# re-benchmark if that memory limit changes or hashing shows up as a
# measured bottleneck.
_ARGON2_TYPE = Type.ID
_ARGON2_MEMORY_COST_KIB = 19_456
_ARGON2_TIME_COST = 2
_ARGON2_PARALLELISM = 1
_ARGON2_HASH_LEN = 32
_ARGON2_SALT_LEN = 16

_password_hasher = PasswordHasher(
    time_cost=_ARGON2_TIME_COST,
    memory_cost=_ARGON2_MEMORY_COST_KIB,
    parallelism=_ARGON2_PARALLELISM,
    hash_len=_ARGON2_HASH_LEN,
    salt_len=_ARGON2_SALT_LEN,
    type=_ARGON2_TYPE,
)

# Precomputed once at import time so login() always has a hash to verify
# against, even when the supplied username doesn't exist - keeps response
# timing the same whether the username is real or not (see routes/auth.py).
DUMMY_PASSWORD_HASH = _password_hasher.hash("not-a-real-password-used-only-for-timing-safety")


def normalize_username(username: str) -> str:
    """Trim surrounding whitespace and fold case so 'Admin' and 'admin' collide."""
    return username.strip().lower()


def hash_password(password: str) -> str:
    return _password_hasher.hash(password)


def verify_password(password: str, password_hash: str) -> bool:
    try:
        return _password_hasher.verify(password_hash, password)
    except (VerifyMismatchError, VerificationError, InvalidHashError):
        return False


# Behavior-metrics submission capability tokens (see
# app/crud/application_behavior_capability.py). Unlike a user-chosen
# password, this is a 256-bit value generated by secrets.token_urlsafe(),
# so a fast cryptographic digest is deliberate here rather than Argon2id:
# offline brute force of the digest is already computationally infeasible
# given the token's entropy, and a slow KDF would only add cost with no
# corresponding security benefit for a value nobody has to memorize.
_CAPABILITY_TOKEN_BYTES = 32


def generate_capability_token() -> str:
    return secrets.token_urlsafe(_CAPABILITY_TOKEN_BYTES)


def hash_capability_token(token: str) -> str:
    return hashlib.sha256(token.encode("utf-8")).hexdigest()


# Idempotency-Key support for POST /applications (see
# app/crud/application.py::create_application_idempotent and
# app/models/application_idempotency_key.py for the full rationale). Only
# this digest of the client-supplied key is ever persisted, never the raw
# key. Unlike hash_capability_token above, this is NOT authorization
# material - a caller picks its own Idempotency-Key, and the backend has no
# way to tell a genuinely random one from a short, guessable-but-format-
# valid one (see app/routes/applications.py's length/charset check, which
# bounds collisions between unrelated keys, not entropy). That is exactly
# why POST /applications never treats "the caller can replay this key" as
# proof of anything beyond "this is the same logical request" - a replay
# only ever returns the original Application, never a behavior-metrics
# capability (see create_application_idempotent's module-level design
# note). A fast SHA-256 digest here is still the right choice - not because
# the key is high-entropy, but because it isn't a secret whose offline
# brute-forcing needs a slow KDF: recovering the raw key from this digest
# only reveals which prior request to recognize as a duplicate, nothing an
# attacker can act on.
def hash_idempotency_key(raw_key: str) -> str:
    return hashlib.sha256(raw_key.encode("utf-8")).hexdigest()


# What *is* hashed alongside the key above is the request payload itself, so
# a replayed key can be checked against the original payload without storing
# the payload a second time.
def hash_idempotency_payload(payload: dict[str, Any]) -> str:
    """Deterministic digest of a JSON-compatible request payload.

    `sort_keys=True` makes the digest independent of dict insertion order;
    the caller is expected to pass something like
    `ApplicationCreate.model_dump(mode="json")`, where every value is
    already a JSON-primitive (Decimal -> str, etc.), so no `default=`
    fallback is needed here.
    """
    canonical = json.dumps(payload, sort_keys=True, ensure_ascii=True)
    return hashlib.sha256(canonical.encode("utf-8")).hexdigest()


class TokenError(Exception):
    """Raised when a JWT is missing, malformed, expired, forged, or the wrong type."""


def create_access_token(subject: str) -> tuple[str, int]:
    """Return (encoded_jwt, expires_in_seconds) for the given subject (admin id)."""
    settings = get_settings()
    now = datetime.now(timezone.utc)
    expires_delta = timedelta(minutes=settings.access_token_expire_minutes)
    payload = {
        "sub": subject,
        "type": TOKEN_TYPE_ACCESS,
        "iat": now,
        "exp": now + expires_delta,
    }
    token = jwt.encode(payload, settings.jwt_secret_key, algorithm=settings.jwt_algorithm)
    return token, int(expires_delta.total_seconds())


def decode_access_token(token: str) -> dict[str, Any]:
    """Decode and validate an access token, raising TokenError on any problem.

    `options={"require": [...]}` makes PyJWT itself reject a token that's
    missing exp/sub/type outright, instead of silently treating an absent
    claim as "nothing to check" (e.g. a token with no `exp` at all would
    otherwise never be recognized as expired). The algorithm is always taken
    from server-side settings, never from the token's own header. A single
    broad `jwt.PyJWTError` catch covers missing claims, expired signatures,
    bad signatures, and malformed structure alike, so no path from a bad
    token reaches the caller as anything other than TokenError, and no
    internal reason leaks past that generic message.
    """
    settings = get_settings()
    try:
        payload = jwt.decode(
            token,
            settings.jwt_secret_key,
            algorithms=[settings.jwt_algorithm],
            options={"require": ["exp", "sub", "type"]},
        )
    except jwt.PyJWTError as exc:
        raise TokenError("Invalid or expired token") from exc

    if payload.get("type") != TOKEN_TYPE_ACCESS:
        raise TokenError("Unexpected token type")

    subject = payload.get("sub")
    if not isinstance(subject, str) or not subject.strip():
        raise TokenError("Missing or invalid subject claim")

    return payload
